### ISSUE TITLE
Issue where messages sent from within promises do not find their way to the react-native app

### ISSUE THREAD

**Issue by nickyromeijn** [janeasystems/nodejs-mobile#13] opened 2017-10-11 08:57 UTC
Hello i'm running into an issue where messages sent from within promises do not find their way to the react-native app. 

My construction is as follows:

**nodejs-project**
```
function connect(callback){
 return businessNetwork.connect('client', 'network', 'PeerAdmin', 'adminpw').then((conn)=>{
   rn_bridge.channel.send("I have connected");
   callback(conn);
  })
  .catch((e)=>callback(e));
}

rn_bridge.channel.on('message', (msg) => {
  rn_bridge.channel.send(msg);
  connect((r)=>rn_bridge.channel.send(r));
});
```

**React-native side:**
```
componentWillMount()
  {
    nodejs.start();
    nodejs.channel.addListener(
      "message",
      (msg) => {
        alert("From node: " + msg);
      },
      this 
    );
  } 
```

Tested the code locally on my machine (without rn-bridge) and it worked fine.

**Comment by jaimecbernardo** [comment] 2017-10-11 09:20
Hi @nickyromeijn ,

Currently the bridge supports sending only strings.
In `connect((r)=>rn_bridge.channel.send(r));` it seems you are trying to send an object through the channel.

Try calling `connect((r)=>rn_bridge.channel.send(JSON.stringify(r)));` instead to see what you get on the other side.

Hope this is helpful.

**Comment by nickyromeijn** [comment] 2017-10-11 09:32
Thanks for the info i didn't know.

However i just tested it and it doesn't seem to make a difference. There's something weird going on. 

```
rn_bridge.channel.on('message', (msg) => {
  rn_bridge.channel.send(msg);
  connect(function(result){
    rn_bridge.channel.send(result)
  });
});
```

Does always echo back the msg sent from react-native so that's fine. However the `connect()` method also has a synchronous call to rn_bridge_channel_send()

example:
```
function connect(callback){
rn_bridge_channel_send("lets see if we can resolve this")

//promise stuff
connection.then((res)=>{
callback("Wooptidoo callback has been called from within resolve") //this is never called? (the message never propagates to react native)
})
}
```
the "lets see if we can resolve this" also only arrives once (the first time) within react-native. All subsequent calls to the `connect()` method and` rn_bridge_channel.send()` calls do not find their way to react-native.

It seems as if the script gets stuck in promises? 

Is there an easy way to debug this btw? Re-compiling the app in the hope that it works takes a long time.

**Comment by nickyromeijn** [comment] 2017-10-11 09:41
I have just tested it with the following code:

```
function test(cb){
  rn_bridge.channel.send("sync test method call....:D");
  cb("callback test method call");
}

rn_bridge.channel.on('message', (msg) => {
  rn_bridge.channel.send(msg);
  test((result)=>rn_bridge.channel.send(result));
});
```

The` rn_bridge.channel.send("sync test method call....:D");` works just fine the callback implementation however, doesn't.

**Comment by jaimecbernardo** [comment] 2017-10-11 10:26
There's the issue that, in React-Native, if you call alert multiple times before the last alert message box has had time to show, it will just show the first alert. I'd advise to try and show the messages in another way.

One way to do it is adding each message received to a state variable and showing that message.

Snippet from the React-Native component.
```
  constructor(props){
    super(props);
    this.state = { lastNodeMessage: "No message yet." };
  }
  componentWillMount()
  {
    nodejs.start();
    nodejs.channel.addListener(
      "message",
      (msg) => {
        this.setState({lastNodeMessage: this.state.lastNodeMessage + '  '+ msg});
      },
      this 
    );
  }
  render() {
    return (
      <View style={styles.container}>
        <Button title="Send to Node"
          onPress={() => nodejs.channel.send('Hi')}
        />
        <Text style={styles.instructions}>
          {this.state.lastNodeMessage}
        </Text>
      </View>
    );
  }
```

**Comment by nickyromeijn** [comment] 2017-10-11 10:36
Thanks, while this cuts out some issues on the react side of things it still isn't a solution to the problem.  `.send` statements from within callbacks or promises just don't seem to propagate to react-native. Is this supposed to work?

**Comment by jaimecbernardo** [comment] 2017-10-11 10:52
I've just tested with your callback code in iOS and I got the `callback test method call` added to `lastNodeMessage` in React-Native and shown.

What's the behavior you're seeing when trying to store and show every message received so far?

**Comment by nickyromeijn** [comment] 2017-10-11 11:04
Strange... i'm testing on IOS as well.

Given the following implementation the behaviour is as follows:

The `"rn_bridge.channel.send("Let's see if we can connect...");"` gets propagated to react-native and is appended to the list of messages; but only for the first call all subsequent messages and calls to the `connect()` method don't do anything. React native receives nothing anymore

```
function connect(){
  rn_bridge.channel.send("Let's see if we can connect...");

  var connectionProfileStore = new composerCommon.EnvConnectionProfileStore();
  var businessNetwork = new            composer.BusinessNetworkConnection({connectionProfileStore:connectionProfileStore});
  businessNetwork.connect('PGBClient', 'pgb-network', 'PeerAdmin', 'adminpw')
    .then((conn)=>{
      rn_bridge.channel.send("We are connected!");
    })
    .catch((e)=>rn_bridge.channel.send("Error while connecting.. :("));
}

rn_bridge.channel.on('message', (msg) => {
  connect();
});
```

**Comment by nickyromeijn** [comment] 2017-10-11 11:20
I think the issue lies in promises. I removed all the promises from my main.js file and tried a simple callback approach; i can confirm that this works. 

After that i rewrote my main.js file to:

```
function test(){
  return new Promise((resolve,reject)=>{
    resolve("Hello world");
  })
}

//Echo every message received from react-native.
rn_bridge.channel.on('message', (msg) => {
  test().then((s)=>{
    rn_bridge.channel.send("Do promises work?")
  });
});
```

These messages never get appended to the message list

**Comment by jaimecbernardo** [comment] 2017-10-11 11:53
Thanks. I've tested it as well and can confirm this issue seems to be promise related.

This needs to be further investigated. In the meanwhile, I can confirm this workaround works:
```
//Echo every message received from react-native.
rn_bridge.channel.on('message', (msg) => {
  setImmediate(function() {
    test().then((s)=>{
      rn_bridge.channel.send("Do promises work?")
    });
  });
});
```

Wrapping the promise code in a `setImmediate` will make it run in the next chance the `uv loop` gets, but this ensures it is called outside of the "scope" we create and close when messages are received from react-native.

Please give it a try. I'm also leaving this issue open so we can track it and people can get help from it as well.

**Comment by nickyromeijn** [comment] 2017-10-11 14:33
Thanks for the fix. I'll try it out later today 👍

**Comment by neogeno** [comment] 2018-03-05 11:52
Any idea when promises will work properly without the SetImmdiate workaround?

**Comment by jaimecbernardo** [comment] 2018-03-05 11:52
A fix for this issue has been committed to both plugins: https://github.com/janeasystems/nodejs-mobile-cordova/commit/dd22c901e718f8529ed32fcd4de0eecdda3c0d6d and https://github.com/janeasystems/nodejs-mobile-react-native/commit/70c9ac3798ca1fa06447ffb5430a1ba7259bccbc

Both fixes have been released to npm, so I'm closing this issue. Thank you.

**Closed by jaimecbernardo** 2018-03-05 11:52 UTC
Labels: bug, cordova plugin, react-native plugin

**Comment by jaimecbernardo** [comment] 2018-03-05 11:54
Hi @neogeno , was closing this issue right before your comment. The fix published is using a setImmediate internally in the plugins. Are you having any issues with that technique?

**Comment by microcai** [comment] 2019-07-09 02:48
this does not solve the root problem at all. see https://github.com/JaneaSystems/nodejs-mobile/issues/209
