### ISSUE TITLE
iOS Node Server down after lock/unlock device

### ISSUE THREAD

**Issue by asielgil88** [janeasystems/nodejs-mobile#211] opened 2019-07-15 01:37 UTC
* **Project**:
* **Version**: pod 'NodeMobile', :git => 'https://github.com/janeasystems/nodejs-mobile.git'
* **Mobile device**: IPad 5 genration
* **Mobile OS and version**: iOS 12.1
* **Development Node.js**:
* **Development platform**:

After device is lock, and then unlock Node server stop working 
all responses for client came as, shouldn't the server have a recovery mechanism

```NSLocalizedDescription=Could not connect to the server., NSErrorFailingURLStringKey=http://localhost:6000/getTransactions, NSErrorFailingURLKey=http://localhost:6000/getTransactions, _kCFStreamErrorDomainKey=1} [-1004]```

**Comment by jaimecbernardo** [comment] 2019-07-15 12:08
This is a duplicate of https://github.com/JaneaSystems/nodejs-mobile/issues/210
Closing it.

**Closed as completed by jaimecbernardo** 2019-07-15 12:08 UTC
Labels: duplicate
