### ISSUE TITLE
Cordova Plugin: Application Version is not updating from config.xml

### ISSUE THREAD

**Issue by patelmayankce** [janeasystems/nodejs-mobile#51] opened 2018-03-06 13:37 UTC
* **Version**:v8.9.4
* **Platform**:64-bit Windows 7
* **Subsystem**:
* **Cordova Version**:7.0.1
* **Ionic Version**:3.19.1

I am building IONIC application, but application version is not taking/updating from config.xml it always shows up 1.0.

**Comment by jaimecbernardo** [comment] 2018-03-06 15:03
Hi @patelmayankce , Thank you for the issue.
Ionic is not one of our currently supported frameworks, though we've had reports of people using it with the cordova plugin.
I'm unfamiliar with Ionic, so I don't understand what this issue is about. Could you provide more information / provide a repo for reproducing the issue?
Thank you, in advance.

**Comment by patelmayankce** [comment] 2018-03-07 05:32
Hello @jaimecbernardo , Thanks for reaching me,

I guess you already know we can change the version of Application using **version** attribute in config.xml ( check out this link https://cordova.apache.org/docs/en/latest/config_ref/#widget ). but after installing **nodejs-mobile** cordvoa plugin app version always says **1.0**. so then after i checkout **https://github.com/janeasystems/nodejs-mobile-cordova/blob/unstable/src/android/build.gradle** and see in gradle file you mentioned **versionCode** & **versionName** default to **1** & **1.0** respective , maybe that create a problem and override application version.

Let me if I missed anything and if you need more detail about the issue.

Thank you very much.

**Comment by jaimecbernardo** [comment] 2018-03-07 11:20
Hi @patelmayankce ,
Thank you for all your help!

A commit has been pushed to solve this issue: https://github.com/janeasystems/nodejs-mobile-cordova/commit/22e5f9ff95d3b185f8ff747a490d0f0e2ad95838

Indeed, Cordova gets its version config.xml https://github.com/apache/cordova-android/blob/rel/6.3.0/bin/templates/project/build.gradle#L171 , but then our plugin was overriding it due to the use of Gradle's `apply from`, which is the technique Cordova uses for applying extensions : https://github.com/apache/cordova-android/blob/rel/6.3.0/bin/templates/cordova/lib/builders/GradleBuilder.js#L166-L170 .

Those lines wouldn't be a problem if the plugin would be treated as a different gradle project, but that isn't the case in Cordova, and `apply from` overrides the Application project's settings. Thank you for noticing it and helping us solve this issue.

I hope this was helpful. Please let us know if this solves your issue or if any more related issues appear.

**Comment by patelmayankce** [comment] 2018-03-07 13:40
Hi @jaimecbernardo,
Yes, that worked,
now can you release this?

**Comment by jaimecbernardo** [comment] 2018-03-07 17:11
Hi @patelmayankce ,

A hotfix release has been published to npm.
https://github.com/janeasystems/nodejs-mobile-cordova/commit/1143e2080de27cdeb587b42d9187e6254ab46634

Closing this issue. Thank you.

**Closed as completed by jaimecbernardo** 2018-03-07 17:11 UTC
