### ISSUE TITLE
[Cordova] Initialization failed

### ISSUE THREAD

**Issue by guilhermelirio** [janeasystems/nodejs-mobile#187] opened 2019-04-17 15:25 UTC
**Cordova**

* **Version**: 8.1.
* **Platform**: Android (8.0.0)

I have an error saying that it is not finding the main.js file

> index.js:25 Received Event: deviceready
> index.js:37 Initialization failed: java.io.FileNotFoundException: www\nodejs-project/main.js

**main.js**
```
const cordova = require('cordova-bridge');

cordova.channel.on('message', function (msg) {
  console.log('[node] received:', msg);
  cordova.channel.send('Replying to this message: ' + msg);
});
```

**index.js**
```
var app = {
  // Application Constructor
  initialize: function() {
      document.addEventListener('deviceready', this.onDeviceReady.bind(this), false);
  },

  // deviceready Event Handler
  //
  // Bind any cordova events here. Common events are:
  // 'pause', 'resume', etc.
  onDeviceReady: function() {
      this.receivedEvent('deviceready');
      startNodeProject();
  },

  // Update DOM on a Received Event
  receivedEvent: function(id) {
    var parentElement = document.getElementById(id);
    var listeningElement = parentElement.querySelector('.listening');
    var receivedElement = parentElement.querySelector('.received');

    listeningElement.setAttribute('style', 'display:none;');
    receivedElement.setAttribute('style', 'display:block;');

    console.log('Received Event: ' + id);
  }
};

app.initialize();

function channelListener(msg) {
  console.log('[cordova] received:' + msg);
}

function startupCallback(err) {
  if (err) {
      console.log(err);
  } else {
      console.log ('Node.js Mobile Engine Started');
      nodejs.channel.send('Hello from Cordova!');
  }
};

function startNodeProject() {
  nodejs.channel.setListener(channelListener);
  nodejs.start('main.js', startupCallback);
  // To disable the stdout/stderr redirection to the Android logcat:
  // nodejs.start('main.js', startupCallback, { redirectOutputToLogcat: false });
};
```
**Folder** _nodejs-project_:
```
main.js
package.json
```

**Comment by jaimecbernardo** [comment] 2019-04-18 08:42
Hi @guilhermelirio ,

Just gave your code a try with `cordova 8.1.2` and `cordova-android 8.0.0`.
It runs as expected for me.

Would you mind sharing a repo with your project and run instructions?

**Comment by leonancg** [comment] 2019-05-06 07:19
Any solutions found?

**Comment by jaimecbernardo** [comment] 2019-05-06 13:17
Hi @leonancg , Do you have more information that you can share? Or a repo to reproduce the error?

**Comment by leonancg** [comment] 2019-05-08 21:29
Hi @jaimecbernardo. I not have repo, but is a empty project, i only follow steps in https://code.janeasystems.com/nodejs-mobile/getting-started-cordova.

Compiled with cordova 7.0.0 / 8.1.2 / 9.0.0. Give same error.

**Comment by jaimecbernardo** [comment] 2019-05-09 15:46
Hi @leonancg ,
This issue seems to be reported by other users recently. Are you on Windows?

**Comment by guilhermelirio** [comment] 2019-05-09 15:58
I was able to build using it like this:
- Cordova 8.1.2
- Android@6.3.0

**Comment by shekhawatbhawani87** [comment] 2019-05-10 10:44
I am having the same error. Infact I edited the files to correct the slash in the path of the file `www\nodejs-project/main.js` to `www\nodejs-project\main.js`. Still I am getting the same error `Initialization failed: java.io.FileNotFoundException: www\nodejs-project/main.js`

I am running with cordova 7.0.0, Android 6.2.3 and windows 10

**Comment by shekhawatbhawani87** [comment] 2019-05-10 10:47
> Hi @leonancg ,
> This issue seems to be reported by other users recently. Are you on Windows?

I am on Windows 10 and I too am getting the same error.

**Comment by leonancg** [comment] 2019-05-11 13:37
@guilhermelirio 
I am on Window 7
Cordova 8.1.2
Android 6.3.0
JavaSDK 8.0_211

**Comment by leonancg** [comment] 2019-05-11 16:16
@guilhermelirio @shekhawatbhawani87 @jaimecbernardo 
Debugging, i found a folder named "www \ nodejs-project". So the problem is actually the backslash. I did not find who writes "file.list", so I modified NodeJS.java by doing overrides.
new File (NodeJS.filesDir + "/" + dir) .mkdirs ();
to:
new File (NodeJS.filesDir + "/" + dir.replace ("www \\", "www /")) mkdirs ();

AND
String src = file;
String dest = NodeJS.filesDir + "/" + file;
to
String src = file.replace ("www \\", "www /");
String dest = NodeJS.filesDir + "/" + file.replace ("www \\", "www /");

This worked for me.

**Comment by jaimecbernardo** [comment] 2019-05-13 07:55
Hi, this issue was caused by paths that come from Windows development machines. Backslashes were not correctly interpreted at runtime in Android, as the more recent comments indicated. This issue has been fixed in the latest released version of `nodejs-mobile-cordova`: https://www.npmjs.com/package/nodejs-mobile-cordova/v/0.3.2
Thank you @leonancg , @guilhermelirio and @shekhawatbhawani87  for your comments and special thanks to @shekhawatbhawani87  for confirming the fix solved this issue.

**Closed as completed by jaimecbernardo** 2019-05-13 07:55 UTC
Labels: question, Android, cordova plugin
