### ISSUE TITLE
How to configure or edit “file.list” under /platforms/android/assets to take correct path?

### ISSUE THREAD

**Issue by shekhawatbhawani87** [janeasystems/nodejs-mobile#191] opened 2019-05-08 07:57 UTC
My question is regarding Node js for mobile from JaneaSystems. I have a web-application which i convert as cordova app. I have followed all the instructions given in the getting started tutorial

https://code.janeasystems.com/nodejs-mobile/getting-started-cordova

However, while triggering the nodejs from js/index.js in the android emulator, I am getting the error as "**Initialization failed: java.io.FileNotFoundException: www\nodejs-project/main.js**"

My index.js file is as follows:

```js
var app = {
    // Application Constructor
    initialize: function() {
        document.addEventListener('deviceready', this.onDeviceReady.bind(this), false);
    },

    // deviceready Event Handler
    //
    // Bind any cordova events here. Common events are:
    // 'pause', 'resume', etc.
    onDeviceReady: function() {
        this.receivedEvent('deviceready');
        startNodeProject();
    },

    // Update DOM on a Received Event
    receivedEvent: function(id) {
        var parentElement = document.getElementById(id);
        var listeningElement = parentElement.querySelector('.listening');
        var receivedElement = parentElement.querySelector('.received');

        listeningElement.setAttribute('style', 'display:none;');
        receivedElement.setAttribute('style', 'display:block;');

        console.log('Received Event: ' + id);
    }
};

app.initialize();

function channelListener(msg) {
    console.log('[cordova] received:' + msg);
}

function startupCallback(err) {
    if (err) {
        console.log(err);
    } else {
        console.log ('Node.js Mobile Engine Started');
        nodejs.channel.send('Hello from Cordova!');
    }
};

function startNodeProject() {
    nodejs.channel.setListener(channelListener);
    nodejs.start('main.js', startupCallback);
    // To disable the stdout/stderr redirection to the Android logcat:
    // nodejs.start('main.js', startupCallback, { redirectOutputToLogcat: false });
};
```

my main.js is as follows:

````js
const cordova = require('cordova-bridge');

cordova.channel.on('message', function (msg) {
  console.log('[node] received:', msg);
  cordova.channel.send('Replying to this message: ' + msg);
});
````
When i execute the command cordova build android a file is created with name "file.list" under /platforms/android/assets whose contents are

````js
www\nodejs-project/main.js
````
Even if i manually change the above to ```www\nodejs-project\main.js``` I still get FileNotFound Exception.

Can anyone please tell me what am i missing as the file main.js is present under nodejs-project ?

Please let me know in case any details are required as i tried to be as thorough as possible.

**Comment by jaimecbernardo** [comment] 2019-05-09 15:42
Hi @shekhawatbhawani87 ,

This issue seems to be occurring to some users, but I've been unable to replicate it yet.
Are you running on Windows, by any chance? The slash direction might be causing this.
Could you please try `www/nodejs-project/main.js`?

**Comment by shekhawatbhawani87** [comment] 2019-05-10 05:44
Hi @jaimecbernardo ,

Thanks for the suggestion. Was waiting for it curiously 

The wrong slash for the path is generated automatically when I build the project. Therefore, even if i change the slash in the above path in "file.dist" after building it overwrites my changes and makes the path again `"www\nodejs-project/main.js"` . If you need, I can zip my project files and send it to you.

**Comment by shekhawatbhawani87** [comment] 2019-05-10 09:56
Also, it doesn't look like 'slash' related problem. I have corrected the slash problem and now the slashes are fine but i am still getting the error.

`
**Received Event: deviceready**, 
**startNodeProject**, 
**startNodeProject - end**,  
**startupCallback**,  
**err in startupCallback is: Initialization failed: java.io.FileNotFoundException: www\nodejs-project\main.js**, 
**Initialization failed: java.io.FileNotFoundException: www\nodejs-project\main.js**
`

**Comment by jaimecbernardo** [comment] 2019-05-13 07:56
Hi, this issue was caused by paths that come from Windows development machines. Backslashes were not correctly interpreted at runtime in Android. This issue has been fixed in the latest released version of `nodejs-mobile-cordova`: https://www.npmjs.com/package/nodejs-mobile-cordova/v/0.3.2
Thank you, @shekhawatbhawani87 , for confirming the fix solved this issue.

**Closed as completed by jaimecbernardo** 2019-05-13 07:56 UTC
Labels: Android, cordova plugin
