### ISSUE TITLE
Assistance Starting Out

### ISSUE THREAD

**Issue by jcrosby10** [janeasystems/nodejs-mobile#32] opened 2018-01-04 17:41 UTC
I am looking to port a web app my company has to mobile using Cordova. They use Node so I can't just plug and play. I set up a new Cordova project to test out what you have to offer but I'm running into some stumbling blocks and would like some general information on how this all works.

I created a new Cordova project and installed your plugin nodejs-mobile-cordova. I then ran `plugins/nodejs-mobile-cordova/install/sample-project/copy-sample-project.sh` according to the [docs](https://code.janeasystems.com/nodejs-mobile/getting-started-cordova) on your website. I can now run the sample app on an Android device but I'm confused on what the code is doing. In a folder called nodejs-project there is a file called main.js and in the js folder is index.js. I can tell index.js is the main starting point for the Cordova app. That I know. However what is the purpose of main.js? I can see in index.js there is a call to nodejs.start passing in "main.js" as a parameter however from what I can tell main.js doesn't do anything. I put in a few console.log and nothing is logged that I can see. I also placed a call to cordova.channel.send and it doesn't work because I get channel is undefined. Here is the code I have in index.js. I can't seem to get the require statements to work as I'm getting require not defined. But if I use cordova.require I get can't find module fs for exapmle. I did run npm install fs prior to this so I know its installed. I can also see the fs folder in the node_modules folder at the root of my Cordova project. Any information you can provide to help get this working would be awesome thank you.

    var app = {
        // Application Constructor
        initialize: function() {
            document.addEventListener('deviceready', this.onDeviceReady.bind(this), false);
        },

        // deviceready Event Handler
        //
        // Bind any cordova events here. Common events are:
        // 'pause', 'resume', etc.
        onDeviceReady: function() {
            this.receivedEvent('deviceready');
            startNodeProject();
            console.log(cordova);

          //   const a = cordova.require("fs");
          //   console.log(a);
          //   const b = cordov.require("browserify-fs");
          //   console.log(b);
          //   const c = cordova.require("electron");
          //   console.log(c);
        },

        // Update DOM on a Received Event
        receivedEvent: function(id) {
            var parentElement = document.getElementById(id);
            var listeningElement = parentElement.querySelector('.listening');
            var receivedElement = parentElement.querySelector('.received');

            listeningElement.setAttribute('style', 'display:none;');
            receivedElement.setAttribute('style', 'display:block;');

            console.log('Received Event: ' + id);
        }
    };
    
    app.initialize();
    
    function channelListener(msg) {
        console.log("[cordova] received:", msg);
    }
  
    function startNodeProject() {
        nodejs.channel.setListener(channelListener);
        nodejs.start("main.js",
            function(err) {
                if (err) {
                    console.log(err);
                }
                else {
                    console.log ("NodeJs Engine Started");
                    nodejs.channel.send("Hello from Cordova!");

                    cordova.channel.send("Sending some information.");
                //  const g2 = cordova.require("http");
                //  const g = require("http");
                //  const d = cordova.require("fs");
                //  console.log(d);
                //  const e = cordova.require("browserify-fs");
                //  console.log(e);
                //  const f = cordova.require("electron");
                //  console.log(f);
                }
            });
    }

**Comment by ksplache** [comment] 2018-01-04 18:00
There is deeper cordova example in the [nodejs-mobile-samples](https://github.com/janeasystems/nodejs-mobile-samples/tree/master/cordova-angularjs) repo.  It has some gulp scripts to allow you to develop / test using a "normal" web app and Node.js and then to also copy the web app and Node.js files to the proper cordova folders to build a cordova app for a device.  The README file attempts to give step by step instructions for the various npm and gulp scripts.

**Comment by jcrosby10** [comment] 2018-01-04 18:27
I took a look at those but we are not using Angular. Is Angular also required to make nodejs-mobile work?

**Comment by ksplache** [comment] 2018-01-04 18:34
No, AngularJS is not required.  You could put any web app in the`src/client` folder and any Node.js server code in the `src/server` folder.  You'll need the code in `src/client/app.js` somewhere in your web app to handle the environment - dev vs. inside cordova - but this code can be moved / ported to any JavaScript file - it's not angular specific.

**Comment by jaimecbernardo** [comment] 2018-01-04 18:34
Hi @jcrosby10 . Thank you for the issue.

I think the main point that you are having issues with is trying to run nodejs-mobile code in the cordova runtime.
The nodejs-mobile code (`main.js`) runs on a different engine than the cordova code (`index.js`). So, nodejs-mobile-cordova is running a Node.js server in the background, in a different environment than the cordova UI, starting in `main.js` inside `nodejs-project`, where a `package.json` file is also present so you can run `npm install` inside for the modules your `nodejs-mobile` runtime depends on. Then you need to communicate between the `cordova` and `nodejs-mobile` runtimes using the provided channel API or any other method of process or thread communication depending on your app's needs.

The sample application runs a echo-like server in `main.js` and cordova's `index.js` starts the server, sends a message, receives the echo and outputs it to the console. You should see the console messages if you have adb connected to your android device/emulator.

I hope this is helpful.

**Comment by jcrosby10** [comment] 2018-01-04 18:46
Yes that is kind of what I was looking for an explanation of what goes in the js folder and what goes in the node-jsproject folder. If I have you correct all Cordova code must go into the js (client) folder and Node code in the node-project (server) folder. That's kind of what I was expecting but I just wanted to make sure since I was not seeing anything when I log in the server side. Which I think I know now is because its running in a different engine. Is this all correct?

**Comment by jaimecbernardo** [comment] 2018-01-04 19:07
You are correct.

Regarding the `console.log()` in the server code the issue is that Node.js outputs to stdout, which Android doesn't show in logcat, while `console.log()` in the cordova code does.

In `nodejs-mobile-react-native` we've started threads to redirect `stdout` and `stderr` to logcat to be helpful in debugging . Here's a link to the changes : https://github.com/janeasystems/nodejs-mobile-react-native/commit/e5fbfd0748757a9c77dc57e4b6c11a68d13aaeac . The threads are started right before starting Node.
If redirecting the streams won't impact your server code, you could try applying those changes to your local version of the plugin in the equivalent file (`nodejs-mobile-cordova/src/android/jni/native-module.cpp`): https://github.com/janeasystems/nodejs-mobile-cordova/blob/unstable/src/android/jni/native-module.cpp

I hope this was helpful. I would like to invite you to join our Gitter channel as well: https://gitter.im/nodejs-mobile/community

**Comment by jcrosby10** [comment] 2018-01-04 19:14
This leaves me with 2 more questions. How do I go about debugging the server code? I've always been able to run Chrome or Safari to attach to a mobile app and debug the JavaScript code from my computer but I'm guessing that wont work with the server code. So how would I debug it? And my last question is how does nodejs-mobile handle browserified code? We use browserify to allow us to use the require function in the browser and in desktop apps. Will using browserify affect how things work in the server code?

**Comment by jaimecbernardo** [comment] 2018-01-04 21:14
Regarding debugging, Node.js has the Node Inspector, but it's not available since the core library is currently built without Intl (i18n), due to having to cross-compile for the mobile platforms, and the inspector depends on Intl: https://github.com/janeasystems/nodejs-mobile/blob/f1ed329c6345773eedea3d908a067ef893c7500f/configure#L1389-L1392 
Intl and the node inspector are features we'd like to include in the Core library eventually. This is the issue where we are tracking the Debugging feature, in case you want to comment / subscribe to it: https://github.com/janeasystems/nodejs-mobile/issues/5

Regarding `browserify`, we haven't test it yet, but according to the module's description it brings `require` so you can use node modules in the browser. Node already has `require`, so I think it would be unneeded, but I'm unaware of what other effects it may have. Best way to know would be to test it.
Please let us know if it causes any issues.

**Comment by jcrosby10** [comment] 2018-01-10 16:49
I'm thinking it won't work because browserify will create a new .js file with everything in it. It will pass in an object to use for each require. It also requires you to attach this generated .js file to an html file in order for it to work. And since the node code is run in a different runtime (a server) browserify wont work because the html files cannot be accessed from there. Is this thought correct?

**Comment by jaimecbernardo** [comment] 2018-01-10 18:36
I'm not familiar enough with `browserify` to be sure, but from your description I'd say you are correct.
I mentioned `browserify` shouldn't be needed because you would be able to require your needed modules from the `nodejs-mobile` code directly. The interface between the `Cordova` UI and the `nodejs-mobile` backend would have to be built on top of the message API or other communication interface, depending on your Application. Though I guess this is true for browser <-> webserver communication as well.
Have you checked if `browserify` works on cordova, for the parts of your project that are supposed to run on the browser? It should work, if all it does is provide the require interface to run some modules in the client side.

**Comment by jcrosby10** [comment] 2018-01-10 20:25
Browserify does work with Cordova. I'm working though it without using browserify as it shouldn't be needed with nodejs-mobile. Thanks for helping me get started.

**Comment by jaimecbernardo** [comment] 2018-03-08 10:04
This issue has been open for a while and was about getting started, so I'm closing it.

**Closed as completed by jaimecbernardo** 2018-03-08 10:04 UTC
Labels: question
