### ISSUE TITLE
Unsupported operating system for nodejs-mobile native builds: Windows 10

### ISSUE THREAD

**Issue by abrarum** [janeasystems/nodejs-mobile#111] opened 2018-08-23 14:51 UTC
Version: output of `8.11.4`
Platform: output of `react-native run-android `64-bit (Windows 10)

Hi,

I've been working on React Native app requiring ccxt library. After installing Nodejs-mobile-react-native and inside the folder of it, I run command: "npm install ccxt". It was successfully installed but when I tried to debug the app with the command "react-native run-android", I got this error: Unsupported operating system for nodejs-mobile native builds: Windows 10

<img width="834" alt="capture" src="https://user-images.githubusercontent.com/7055212/44532936-c1a48c00-a70d-11e8-9e1b-b22ef91de524.PNG">

**Comment by jaimecbernardo** [comment] 2018-08-23 16:58
Hi @abrarum , 
This seems to be a duplicate of the most recent issue: https://github.com/janeasystems/nodejs-mobile/issues/110
Would you mind taking a look there to see if it helps, or re-open it and continue the conversation there?

**Closed as completed by jaimecbernardo** 2018-08-23 16:58 UTC
Labels: duplicate
