### ISSUE TITLE
Node takes a long time to initialize (Android <= 6)

### ISSUE THREAD

**Issue by HZSamir** [janeasystems/nodejs-mobile#26] opened 2017-11-29 10:46 UTC
Hello,
In a rather simple use case the node process takes a huge amount of time to initialize (somewhere between 2 to 4 minutes) in debug, slightly less in prod

My file:
```javascript
var rn_bridge = require('rn-bridge');
var uuidv1 = require('uuid/v1');
var rp = require('request-promise');
// My imports

// Echo every message received from react-native.
rn_bridge.channel.on('message', (msg) => {
  switch(msg) {
    case 'versions':
    rn_bridge.channel.send('You\'ve asked for versions!');
    break;

    case 'test':
    rn_bridge.channel.send(`BIG test! ${uuidv1()}`);
    break;

    case 'rp':
    rp('http://www.google.com')
    .then(function (htmlString) {
        // Process html...
        rn_bridge.channel.send('Success')
    })
    .catch(function (err) {
        // Crawling failed...
        rn_bridge.channel.send('Error')
    });
    break;

    default:
    rn_bridge.channel.send(msg);
    break;
  }
} );

// Inform react-native node is initialized.
rn_bridge.channel.send("Node was initialized.");
```

What is causing this? And is there some fix?
Thank you

**Comment by jaimecbernardo** [comment] 2017-11-29 21:48
Hi @Unforgiven-wanda,
Thanks for the issue.

What is your current environment? I'm assuming you're using the `nodejs-mobile-react-native` plugin from the code, but where are you running it? iOS, android? emulator? architecture?
What are you experiencing?
Some more details would be useful.

Thanks, in advance.

**Comment by HZSamir** [comment] 2017-11-30 07:25
In dev mode running on either an emulator (Genymotion Android 6.0, Ubuntu, Node x64) or a device running Android 6.0 (Haven't had the chance to try this on IOS)
The project is running the latest version of RN 0.50
As explained above, I thought at first the problem might come from running in dev mode, as it is noticeably slower than the release apk, but even on the released APK the problem persists.

I apologize for not specifying that I was referring to `nodejs-mobile-react-native`, I kinda forgot that you have the equivalent for native and Cordova

Edit: After some further testing it seems this issue occurs whenever I add any dependency (in this case `request`): Understand that the node process starts almost immediately when I have no dependencies, but adding anything else slows it down to a crawl.

**Comment by jaimecbernardo** [comment] 2017-11-30 15:42
Hi @Unforgiven-wanda ,
Thanks for the additional information.

I've been able to test your sample (with `uuid`, `request-promise` and `request`) on Windows, with a x86_64 Android 6.0 simulator that comes with Android Studio. I've also tried it on an armv7 Android 7.0 physical device. It's taking some seconds to initialize node in both cases.

From your further information I can confirm that removing node modules from the `nodejs-project` makes the initialization time non-noticeable.
This is probably caused by the limitation of having to copy the `nodejs-project` from the application's `apk` to the Application's documents path:
https://github.com/janeasystems/nodejs-mobile-react-native/blob/bbf5c46566ab3b1789bfe633453f9d792f51f858/android/src/main/java/com/janeasystems/rn_nodejs_mobile/RNNodeJsMobileModule.java#L88-L97

The reason for this copy is that node expects to be run on a system with file paths, where it will try to look for `.js` files and modules when you require something or try to start node on a `.js` file. An Android APK, where assets like `nodejs-project` are located, is like a big zip file, so we first copy `nodejs-project` files from the APK to the Documents folder.

I think that this copy process might be causing the slowdown you are observing, due to the big number of files in `nodejs-project/node_modules` that are copied on node startup.

Some mechanism to detect if the files were already copied and there isn't a new version would be an improvement, as it would be a one time only operation. Another path to solve this might be to figure another way to have node recognize the `nodejs-project` file inside the APK and seamlessly load from there. Ideas and discussion on how to solve this are welcome.

Though in your case, you report having delays of a few minutes, so it might be something different altogether. Are you testing on a really old device or is the app operating in the SD card so every file operation takes longer?

This issue should be left open, since it contains valuable information until there's a solution for this.

**Comment by d0bz** [comment] 2017-12-04 19:24
I have also same problem. I have noticed that when node_modules is about 20MB with 2000 files inside then loading takes about 3-4 minutes and when node_modules size is about is 5-10MB then about 1 minute. So it seems to be linear time consuming process.

Using physical device, Android 6.0 https://www.gsmarena.com/huawei_mate_s-7533.php

**Comment by stoically** [comment] 2017-12-09 05:20
Since I ran into this performance problem myself, I looked into reading directly from the APK as possible solution. Seems like there was a discussion about [packaging node_modules](https://github.com/nodejs/node/issues/1278) and someone built something to make it work [per module](https://github.com/bmeck/noda-loader) - doesn't seem an easy but doable task.

**Comment by jaimecbernardo** [comment] 2017-12-11 15:11
Thanks for everyone's comments.

This performance issue is verified to affect devices on older Android Versions ( 6 and lower ) and was also an issue that had to be solved on JXCore, a project the team worked on.
You can expect a fix to be released in the future.

**Comment by jaimecbernardo** [comment] 2018-01-02 17:36
This performance issue has been [fixed](https://github.com/janeasystems/nodejs-mobile-cordova/commit/0773a17bafe4c69862315a6561d89685d53b73e5) for the `nodejs-mobile-cordova` plugin in its latest npm release `v0.1.2`.

We are currently working on the fix for the `nodejs-mobile-react-native` plugin.

**Comment by stoically** [comment] 2018-01-02 18:45
That's great news. Though, it should be noted, that it will still take minutes the first time the app starts or after the app gets updated.

**Comment by stoically** [comment] 2018-01-02 19:02
To clarify, what actually got implemented was the check that the node_modules folder doesn't get copied on every app run, but only on the first startup and when the app updates. From my personal perspective this approach still doesn't make nodejs-mobile feasible for android devices <=6. The average user skips Websites because they take longer than 2s to load - to expect them to wait minutes for an app to start is optimistic to say the least. I totally understand that implementing an on the-fly-reader would mean a lot of overhead tho, so yeah, I guess we have to deal with it. Maybe show the user a "This will take a while. Feel free to close the app, we will notify you when it's ready" dialog?

On a side-note, anyone knows why this works so fast on Android7+? I mean, it executes the same Copying of Assets code if I'm not mistaken - shouldn't that be comparable slow?

**Comment by jaimecbernardo** [comment] 2018-01-02 19:19
Hi @stoically,

There are checks to run the copy only after an update or install, but the whole copy has been optimized.
The main problem with the original implementation was that it used `AssetManager.list()`, which was very slow up to Android 6.
Now the list of the assets is computed at build time, so that issue is gone.
Our tests on a Nexus 6P downgraded to Android 6 saw the reduction of startup time, from minutes to 2 seconds with a sizeable `node_modules` (a total of 50MB, 863 folders and 3785 files), which could be acceptable for "setup time", as it would only run on a new install / update.

Please let us know if the issue persists on your `nodejs-mobile-cordova` application after the update.

**Comment by stoically** [comment] 2018-01-02 19:58
I've tested with nodejs-mobile-cordova version 0.1.2 on Genymotion Custom Phone 6.0.0 API 23 and on a real device running Android 6.0.1.

Genymotion
First start: 1m 25s
Second+ start: 2-3s

Real device
First start: 15s
Second+ start: 8s

node_modules size is 52M, 4789 files and 694 directories.

I didn't test on a real device before writing my reply, but only on the Genymotion Device, sorry about that. I guess 15s for the first/updated start is definitively feasible. Thanks for your work!

**Comment by jaimecbernardo** [comment] 2018-01-02 20:44
Thank you for your feedback, @stoically .
Would you mind sharing what real device you tested it on? Thanks, in advance.

**Comment by stoically** [comment] 2018-01-02 21:24
Sure, the test real device is a Moto G4 Play

**Comment by DiegoNegri** [comment] 2018-01-09 09:36
Looks great, looking forward for a porting on nodejs-mobile-react-native

**Comment by jaimecbernardo** [comment] 2018-01-16 15:46
This performance issue has been [fixed](https://github.com/janeasystems/nodejs-mobile-react-native/commit/ae837b29c928bdd964db79abff06ddf925af097a) for the `nodejs-mobile-react-native` plugin in its latest npm release `v0.1.3`.

! Attention: This version also has a breaking change where you have to specify the name of the node entrypoint. This means replacing `nodejs.start();` with `nodejs.start('main.js');` on current projects and you should be good to go.

I'm closing the issue, as the fix has been released for both plugins.

**Closed as completed by jaimecbernardo** 2018-01-16 15:46 UTC
Labels: Android, cordova plugin, react-native plugin

**Comment by jaimecbernardo** [comment] 2018-03-07 12:21
Hi @stoically ,

It is possible that your asset copy was still slow due to the lists not being created. If your workflow is to run `cordova run` without running `cordova build` before, the lists won't be created.

A commit has been pushed to solve this issue and should be out in the next release:
https://github.com/janeasystems/nodejs-mobile-cordova/commit/c7230644e2ba7f0a2bce139ee5ecf5f9b98c7c15

In the meanwhile, a workaround that would work with the current plugin's released version would be to run `cordova build android` before `cordova run android`.

Please let us know if this fixes your issue.
