### ISSUE TITLE
Rerun node on react-native

### ISSUE THREAD

**Issue by triracle97** [janeasystems/nodejs-mobile#276] opened 2020-07-31 09:22 UTC
Im trying to run a node application in my react-native application, but when i turn node application off, there is no way to turn it on again. As mentioned in nodejs-mobile-react-native README:

> Attention: The Node.js project runs on a dedicated thread and as a singleton, so only the first nodejs.start() command will make any effect, as further calls will not start new threads. This means that if you use react-native's hotreload functionality you won't see any changes in the Node.js project. 

So how can i rerun node application after turning it off ?

**Comment by jaimecbernardo** [comment] 2020-08-10 11:02
Looks like a duplicate of:
https://github.com/JaneaSystems/nodejs-mobile/issues/166

**Closed as completed by jaimecbernardo** 2020-08-10 11:02 UTC
Labels: duplicate
