### ISSUE TITLE
Please support binding for Xamarin Platform

### ISSUE THREAD

**Issue by coffice12** [janeasystems/nodejs-mobile#258] opened 2020-04-11 13:27 UTC
Please support binding for Xamarin Platform

Android
iOS

**Comment by jaimecbernardo** [comment] 2020-04-29 23:17
Hi, This is currently not planned. It's a duplicate of https://github.com/JaneaSystems/nodejs-mobile/issues/41 as well.

**Closed as completed by jaimecbernardo** 2020-04-29 23:17 UTC
Labels: duplicate, question
