### ISSUE TITLE
nodejs-mobile-cordova: Android Expected NDK STL shared object file libc++_shared.so

### ISSUE THREAD

**Issue by mohlsen** [janeasystems/nodejs-mobile#178] opened 2019-03-14 13:15 UTC
* **Project**: nodejs-mobile-cordova
* **Version**: 0.2.4
* **Mobile device**: Samsung Galaxy S9
* **Mobile OS and version**: Android 9
* **Development Node.js**: v8.6.0
* **Development platform**: Darwin 17.7.0 Darwin Kernel Version 17.7.0

We attempted to upgrade our project from nodejs-mobile-cordova v0.2.3 to v0.2.4.  Upon doing so (the only change was the plugin version), we receive an error when running `cordova run android`.  I updated the sample *cordova-angularjs* project [in this fork](https://github.com/mohlsen/nodejs-mobile-samples/commit/42dff761aecd4ced742fd1f1b142be2b84653cc8) and receive the same error.

What version of the NDK is required?  The [docs](https://code.janeasystems.com/nodejs-mobile/getting-started-android#android-sdk-requirements) list NDK v15 as the min version,  I have *NDK 17.1.4828580* installed and in my path. Cordova 7.1.0 installed.  

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> Expected NDK STL shared object file at /Users/XXX/Library/Android/sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/libs/armeabi/libc++_shared.so

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 0.998 secs
Error: /Users/XXX/Development/nodejs-mobile/nodejs-mobile-samples/cordova-angularjs/cordova/ExampleCordovaAngular/platforms/android/gradlew: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> Expected NDK STL shared object file at /Users/XXX/Library/Android/sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/libs/armeabi/libc++_shared.so

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

```

**Comment by mohlsen** [comment] 2019-03-14 13:46
Installed NDK 19.1.  Same error.  Its looking for `/ndk-bundle/sources/cxx-stl/llvm-libc++/libs/armeabi/libc++_shared.so` but the file is located at `ndk-bundle/sources/cxx-stl/llvm-libc++/libs/armeabi-v7a`

**Comment by jaimecbernardo** [comment] 2019-03-14 18:06
Hi @mohlsen ,

Thank you for reporting the issue.
I've been able to replicate the issue, which seems to be caused by `cordova-android 6.3.0`, which is installed by `cordova 7.1.0`, and tries to build for the `armeabi` CPU architecture.
The `armeabi` CPU architecture is not supported by the plugin and is removed from the NDK since `r17`.

Before, `nodejs-mobile-cordova` was forcing the Application to only build for the `armeabi-v7a` and `x86` architectures. This was disabled in `nodejs-mobile-cordova v0.2.4` to allow building for 64-bit architectures as well and not override the architectures targeted by Cordova.

A fix will be tested for only building supported architectures when an `abiFilter` is not already set.

In the meanwhile, upgrading to `cordova-android 6.4.0` or staying in `nodejs-mobile-cordova 0.2.3` are the recommended workarounds.

**Comment by jaimecbernardo** [comment] 2019-03-14 20:03
The mentioned fix was released as part of `nodejs-mobile-cordova v0.2.5`:
https://www.npmjs.com/package/nodejs-mobile-cordova/v/0.2.5

It should build correctly with `cordova-android 6.3.0`, now.

**Comment by mohlsen** [comment] 2019-03-15 13:45
This release fixed the issue.  https://github.com/janeasystems/nodejs-mobile-cordova/commit/bc3c596a88ddae729b60e3c3ac3b4def42952111 looks good.  Tested in both the sample app and our app.  

Thanks!

**Comment by jaimecbernardo** [comment] 2019-03-15 17:10
Thank you for the feedback! Closing the issue.

**Closed as completed by jaimecbernardo** 2019-03-15 17:10 UTC
Labels: Android, cordova plugin
